name: Test and Lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check-format
      - run: pnpm run lint

  test_vue2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.0
      - run: pnpm add -g @vue/cli
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test:vue2

  test_vue3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.0
      - run: pnpm add -g @vue/cli
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test:vue3
